FROM ubuntu:16.04

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

RUN echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y mongodb-org-server python-pip && mkdir -p /data/db

RUN apt-get install -y supervisor

COPY files/mongo_supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN mkdir -p /var/log/supervisor

RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
RUN sed -i 's/\/var\/log\/mongodb\/mongod.log/\/var\/minerva\/mongod.log/' /etc/mongod.conf

EXPOSE 27017

CMD ["/usr/bin/supervisord"]
